package:
  name: libmlx5-cos6-x86_64
  version: 1.0.2

source:
  - url: http://mirror.centos.org/centos/6.10/os/x86_64/Packages/libmlx5-1.0.2-1.el6.x86_64.rpm
    sha256: 041aced823d5a339ca7209ec7169616aa90275361316936c2b2bde2f7982d174
    folder: binary
  - url: http://vault.centos.org/6.10/os/Source/SPackages/libmlx5-1.0.2-1.el6.src.rpm
    folder: source

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'



about:
  home: https://www.openfabrics.org/
  license: GPLv2 or BSD
  license_family: GPL2
  summary: "(CDT) Mellanox Connect-IB InfiniBand HCA Userspace Driver"
  description: |
        libmlx5 provides a device-specific userspace driver for Mellanox Connect-IB
        HCAs for use with the libibverbs library.
