package:
  name: libnl-cos6-x86_64
  version: 1.1.4

source:
#  - url: http://mirror.centos.org/centos-6/6.10/os/x86_64/Packages/libnl-devel-1.1.4-2.el6.x86_64.rpm
#    sha256: 6c1749d9f8e9cbe31c84067a7da5f9861c2cd61a0df9b83107b6d045f24a766a
#    folder: binary
  - url: http://mirror.centos.org/centos-6/6.10/os/x86_64/Packages/libnl-1.1.4-2.el6.x86_64.rpm
    sha256: 03a7235e747695208a2633fd6515a39377a9b06b7aa866bda1a1e1eabf418869
    folder: binary


outputs:
  - name: libnl-cos6-x86_64
    noarch: generic

    about:
      home: Netlink Library Suite
      license: MIT
      license_family: MIT
      summary: Netlink is a IPC mechanism primarly between the kernel and user space processes
      description: |
        Netlink is a IPC mechanism primarly between the kernel and user space processes
