{% set ucx_version = "1.7.0.dev" %}
{% set ucx_commit = "2d85597" %}  # from Akshay's ucx-cuda branch
{% set ucx_py_version = "0.1.0.dev" %}
{% set ucx_py_commit = "c58b2ac" %}  # from rapidsai's devel branch
{% set number = "1" %}

package:
  name: ucx-split

source:
  - git_url: https://github.com/Akshay-Venkatesh/ucx
    git_rev: {{ ucx_commit }}
    folder: ucx
  - git_url: https://github.com/rapidsai/ucx-py
    git_rev: {{ ucx_py_commit }}
    folder: ucx-py

build:
  skip: true  # [not linux]

outputs:
  - name: ucx-proc
    version: 1.0.0
    build:
      number: 0
      string: "{{ ucx_proc_type }}"
    about:
      home: https://github.com/conda-forge/ucx-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU UCX build.

  - name: ucx
    version: "{{ ucx_version }}{{ number }}+g{{ ucx_commit }}"
    build:
      number: {{ number }}
      string: "h{{ PKG_HASH }}_{{ number }}_{{ ucx_proc_type }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("nvcc") }}         # [ucx_proc_type == "gpu"]
        - {{ cdt("libnl") }}
        - {{ cdt("libibverbs-devel") }}
        - {{ cdt("librdmacm-devel") }}
        - {{ cdt("numactl-devel") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        - ${PREFIX}/bin/ucx_info -v         # [ucx_proc_type != "gpu"]
    about:
      home: https://github.com/openucx/ucx
      license: BSD-3-Clause
      license_family: BSD
      license_file: ucx/LICENSE
      summary: Unified Communication X.

  - name: ucx-py
    version: "{{ ucx_py_version }}{{ number }}+g{{ ucx_py_commit }}"
    build:
      number: {{ number }}
      skip: true  # [py<36]
      string: "py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ number }}_{{ ucx_proc_type }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("nvcc") }}         # [ucx_proc_type == "gpu"]
        - {{ cdt("libnl") }}
        - {{ cdt("libibverbs") }}
        - {{ cdt("librdmacm") }}
      host:
        - python
        - setuptools
        - cython
        - ucx
      run:
        - python
        - {{ pin_subpackage("ucx", exact=True) }}
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx-py.sh
    test:
      imports:
        - ucp
    about:
      home: https://github.com/rapidsai/ucx-py
      summary: Python bindings for UCX

extra:
  recipe-maintainers:
    - jakirkham
    - TomAugspurger
