{% set ucx_version = "1.5.1" %}
{% set number = "0" %}

package:
  name: ucx-split

source:
  url: https://github.com/openucx/ucx/archive/v1.5.1.tar.gz
  sha256: e612fd334f75e248765d7c15c4f93f47bfa9fcb34dcebd0878436a7065673a50

build:
  skip: true  # [not linux]
  missing_dso_whitelist:
    - libibverbs.so
    - libnl-3.so
    - libnl-route-3.so
    - librdmacm.so


outputs:
  - name: ucx-proc
    version: 1.0.0
    build:
      number: 0
      string: "{{ ucx_proc_type }}"
    about:
      home: https://github.com/conda-forge/ucx-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU UCX build.

  - name: ucx
    version: {{ ucx_version }}
    build:
      number: {{ number }}
      string: "h{{ PKG_HASH }}_{{ number }}_{{ ucx_proc_type }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("nvcc") }}  # [ucx_proc_type == "gpu"]
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        - ${PREFIX}/bin/ucx_info -v         # [ucx_proc_type != "gpu"]
    about:
      home: https://github.com/openucx/ucx
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.

extra:
  recipe-maintainers:
    - jakirkham
    - TomAugspurger
