{% set ucx_version = "1.7.0.dev" %}
{% set ucx_commit = "4df4fb99c" %}  # from OpenUCX's master branch
{% set number = "0" %}

package:
  name: ucx-split

source:
  git_url: https://github.com/openucx/ucx
  git_rev: {{ ucx_commit }}

build:
  skip: true  # [not linux]

outputs:
  - name: ucx-proc
    version: 1.0.0
    build:
      number: 0
      string: "{{ ucx_proc_type }}"
    about:
      home: https://github.com/conda-forge/ucx-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU UCX build.

  - name: ucx
    version: "{{ ucx_version }}{{ number }}+g{{ ucx_commit }}"
    build:
      number: {{ number }}
      string: "h{{ PKG_HASH }}_{{ number }}_{{ ucx_proc_type }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("nvcc") }}         # [ucx_proc_type == "gpu"]
        - {{ cdt("libnl") }}
        - {{ cdt("libibverbs-devel") }}
        - {{ cdt("librdmacm-devel") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
      host:
      run_constrained:
        - ucx-proc * {{ ucx_proc_type }}
    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/bin/ucx_info"
        # Requires driver for GPU test.
        - ${PREFIX}/bin/ucx_info -v         # [ucx_proc_type != "gpu"]
    about:
      home: https://github.com/openucx/ucx
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.

extra:
  recipe-maintainers:
    - jakirkham
    - TomAugspurger
