{% set name = "pdf2svg" %}
{% set version = "0.2.3" %}
{% set sha256 = "4fb186070b3e7d33a51821e3307dce57300a062570d028feccd4e628d50dea8a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/dawbarton/pdf2svg/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - poppler
    - cairo
  run:
    - poppler
    - cairo

test:
  commands:
    - hash pdf2svg

about:
  home: https://github.com/dawbarton/pdf2svg
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: A simple PDF to SVG converter using the Poppler and Cairo libraries

extra:
  recipe-maintainers:
    - jakirkham
